# -*- coding: utf-8 -*-
"""Conversor_de_Moedas.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zkHpYj87Hizi4PiuZPoM8mYGmZwqY7Q6

<a href="https://colab.research.google.com/github/SteffanySympson/Blue-mod-1/blob/main/Conversor_de_Moedas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Conversor de moedas
Crie um programa que solicite um um valor em real ao usuário e converta esse valor, para:

DOLAR,
EURO,
LIBRA ESTERLINA,
DÓLAR CANADENSE,
PESO ARGENTINO,
PESO CHILENO.
Para esse exercício você precisará realizar uma pesquisa para saber a cotação de cada moeda em real. Mostrar o resultado no formato $ XXXX.XX
"""

#Dólar Americano = 5,04
# Euro = 6,13
# Libra Esterlina = 7,13
# Dólar Canadense = 4,16
# Peso Argentino = 0,053
# Peso Chileno = 0,0070

# Texto solicitando entrada de valor em reais
# Print dos valores multiplicados
# Print com o $
#converter valor para float

DolarAmericano = 5.04
Euro = 6.13
LibraEsterlina = 7.13
DolarCanadense = 4.16
PesoArgentino = 0.053
PesoChileno = 0.0070

nome = input ("Qual o seu nome? ")
print ("Olá!!! Bem vindo (a) " +nome, "ao conversor de moedas!")
print ()
ValorReal = float (input ("Informe o valor em Reais - R$ - para o resultado de conversão: "))
print ()
print (f"Dólar Americano: $ {(ValorReal / DolarAmericano):.2f}")
print ()
print (f"Euro: $ {(ValorReal / Euro):.2f}")
print ()
print (f"Libra Esterlina: $ {(ValorReal / LibraEsterlina):.2f}")
print ()
print (f"Dolar Canadense: $ {(ValorReal / DolarCanadense):.2f}")
print ()
print (f"Peso Argentino: $ {(ValorReal / PesoArgentino):.2f}")
print ()
print (f"Peso Chileno: $ {(ValorReal / PesoChileno):.2f}")
print ()