# -*- coding: utf-8 -*-
# Desafio da Avinhação.ipynb

# Automatically generated by Colaboratory.

# Original file is located at
#     https://colab.research.google.com/drive/1fr1U1V_uHFTRMKH5GhAx4QSWihyIKYCd

# Escreva um programa que faça o computador “pensar” em um número inteiro entre 0 e 10 e peça para o usuário tentar descobrir qual foi o número escolhido pelo computador.
# O programa deverá escrever na tela se o usuário venceu ou perdeu.
# COMPLEMENTO: Informar quantas tentativas foram necessárias até acertar


import random 

nome = input ("Olá, nos conte seu nome: ")
print (nome.capitalize() , ", Bem vindo (a) ao nosso jogo da advinhação!")
print ()
print ("Tente advinhar um número de 0 a 10")
num_user = ""
tentativas = 0
num = random.randint (0,10)

while (num_user != num):
  num_user = int (input ("Qual número eu pensei: "))
  if num == num_user:
    print ("Você é mágico, advinhou meu pensamento!")
  else:
    print ("Não foi dessa vez, tente novamente! ")
    tentativas += 1
print (f"Tentativas: {tentativas}")   