# -*- coding: utf-8 -*-
"""Desafio do Caixa.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1E3LvDL4t1X74BiyYLj6djC6jLIg59ZoM

Faça um Programa para um caixa eletrônico. O programa deverá perguntar ao usuário a valor do saque e depois informar quantas notas de cada valor serão fornecidas. As notas disponíveis serão as de 1, 5, 10, 50 e 100 reais. O valor mínimo é de 10 reais e o máximo de 600 reais. O programa não deve se preocupar com a quantidade de notas existentes na máquina.

Exemplo 1: Para sacar a quantia de 256 reais, o programa fornece duas notas de 100, uma nota de 50, uma nota de 5 e uma nota de 1;

Exemplo 2: Para sacar a quantia de 399 reais, o programa fornece três notas de 100, uma nota de 50, quatro notas de 10, uma nota de 5 e quatro notas de 1.
"""

print ("Caixa eletrônico do desafio")
print()

saque = float (input ("Informe o valor que deseja sacar (Min.: R$ 10,00 - Máx.: R$ 600,00): R$ ").replace(',','.'))

while saque < 10 or saque > 600:
    print ("Valor indisponível.")
    saque = float (input ("Informe o valor que deseja sacar (Min.: R$ 10,00 - Máx.: R$ 600,00): R$ ").replace(',','.'))

else:
  print(f"Você está sacando: R$ {saque}:.2f")
  nota_cem = int (saque/100)
  saque = saque % 100
   
  nota_cinquenta = int (saque/50)
  saque = saque % 50
    
  nota_dez = int (saque/10)
  saque = saque % 10
    
  nota_cinco = int (saque/5)
  saque = saque % 5     
    
  nota_um = int (saque/1)
  saque = saque % 1

print ("Você está recebendo:")

print (f"{nota_cem} notas de R$ 100,00")
print (f"{nota_cinquenta} notas de R$ 50,00")
print (f"{nota_dez} notas de R$ 10,00")
print (f"{nota_cinco} notas de R$ 5,00")
print (f"{nota_um} notas de R$ 1,00")
print ()
print ("Volte Sempre!")