# -*- coding: utf-8 -*-
"""exemplos_aula03_condicionais.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1l0uBZlti575F9Ge6V-eVyDiMGZuNugYc

<a href="https://colab.research.google.com/github/gpereira-blueedtech/Blue_T3C5_mod1/blob/main/exemplos_aula03_condicionais.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>
"""

num1 = int(input("Digite um número: "))
num2 = int(input("Digite outro número: "))

if num1 > num2:
    print("O número 1 é maior")
    print("A matemática ainda está correta.")
    print("Que bom!!")
elif num1 < num2 :   # else if
    print("O número 2 é maior!")
else:
    print("Os dois são iguais")

print()
print("Fim do programa.")

"""Se fizer sol, eu vou correr. Senão, se chover, eu vou fazer Yoga. Depois vou fazer compras."""

resposta = input("Você tem mais de 18 anos? [SIM / NÃO]")
dinheiro = input("Você tem dinheiro? [SIM / NÃO]")

if resposta.upper().strip() == "SIM" and dinheiro.upper().strip() == "SIM":
  print("Então me paga uma cerveja!")
elif resposta.upper().strip() == "SIM" and dinheiro.upper().strip() == "NAO":
  print("Então vou te pagar uma cerveja!")
elif resposta.upper().strip() == "NÃO" or resposta.upper().strip() == "NAO":
  print("Então te pago uma coca.")
else:
  print("Aprende a digitar então!")

### IFS aninhados

resposta = input("Você tem mais de 18 anos? [SIM / NÃO]")

if resposta.upper().strip() == "SIM":
  dinheiro = input("Você tem dinheiro? [SIM / NÃO]")
  if dinheiro.upper().strip() == "SIM":
      print("Então me paga uma cerveja!")
  else:
      print("Então vou te pagar uma cerveja!")
elif resposta.upper().strip() == "NÃO" or resposta.upper().strip() == "NAO":
  print("Então te pago uma coca.")
else:
  print("Aprende a digitar então!")