# -*- coding: utf-8 -*-
"""resolucao_exercicios_aula03_strings.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CWtMDMc2QBqrLQAvx0iz1ZJHlNAC90qk

<a href="https://colab.research.google.com/github/gpereira-blueedtech/Blue_T3C5_mod1/blob/main/resolucao_exercicios_aula03_strings.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

01 – Escreva um programa que deve receber o nome completo do usuário e retornar uma saudação com o nome no formato adequado (todas as primeiras letras em maiúsculas).
"""

nome = input("Olá, qual o seu nome? ").title() # Tratei o nome logo no input e armazenei com o novo formato.
print(f"Bem-vindo(a) {nome}!")

### ALTERNATIVA

# nome = input("Olá, qual o seu nome? ") # Armazenei o nome do jeito que o usuário entrou, e tratei na hora de dar o print.
# print("Bem-vindo(a)", nome.title() + "!")

"""02 - Escreva um programa que solicite uma frase ao usuário e escreva a frase toda em maiúscula e sem espaços em branco.

"""

frase = input("Digite uma frase: \n")
print(frase.upper().replace(" ",""))

"""03 – Faça um programa que solicite a altura e o peso do usuário, e calcule o seu IMC. Os dados entrados precisam ser corrigidos pelo programa (trocando “,” por “.” e eliminando espaços e letras extras)."""

altura = float(input("Qual a sua altura?\nM: ").lower().replace(',' , '.').replace(" ","").replace("m",""))
peso = float(input("Qual o seu peso?\nKg: ").lower().replace(',' , '.').replace(" ","").replace("k","").replace("g",""))
imc = peso / (altura**2)
print(f"O seu IMC é: {imc:.1f}")