# -*- coding: utf-8 -*-
"""Exemplos_T3C5_Aula02.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ADq-sN6JNZcr9W8rwWf-uTqqrAWBc0sk
"""

# Sempre que eu uso esse sinal no começo da linha, ele ignora tudo que estiver escrito.

# Primeiros exemplos de print:
print('Olá Mundo!!')
print("Eu fiz um novo código!! Eba!!!")
print()


# Criando variáveis
var1 = 'Blue'
var2 = 25
var3 = 15.87
var4 = True

# Printando as variáveis criadas
print(var1)
print(var2)
print(var3)
print()

# Verificando o tipo de cada variável
# type(var) -> Sintaxe para informar o tipo da variável
print(type(var1))
print(type(var2))
print(type(var3))
print(type(var4))

#Criando várias variáveis
vara, varb, varc = 10, 10.78, "Blue"
var_d = "Aluno "

print(var_a)
print(var_b)
print(var_c)
print()

# Printando, vários valores
print(var_a, var_b, var_c)
print()

print("A var_a recebeu o valor", var_a)
print(var_d + var_c)

# Comando input

nome = input("Digite o seu nome: ")
num1 = int(input("Digite um número: "))
num2 = float(input("Digite o segundo número: "))

print("O seu nome é:", nome)
print(num1)
print(num2)
print()
print(type(num1))
print(type(num2))

# Operadores aritméticos:
num1 = float(input("Digite o primeiro número: "))
num2 = float(input("Digite o segundo número: "))

print("A soma dos números é:", num1 + num2)
print("A subtração dos números é:", num1 - num2)
print("A multiplicação dos números é:", num1 * num2)
print("A divisão dos números é:", num1 / num2)
print("A divisão inteira dos números é:", num1 // num2)
print("A exponenciação dos números é:", num1 ** num2)
print("O resto da divisão dos númerso é:", num1 % num2)

num1 = float(input("Digite o primeiro número: "))
num2 = float(input("Digite o segundo número: "))

print(num1 == num2)

# Operações Matemáticas
nome=(input("Digite seu nome:"))
print("Vamos aprender operações", nome+"?")
num1 = float(input("Digite um numero: "))
num2 = int(input("Digite outro numero: "))
print()
print("A soma dos números será:", num1 + num2)
print("A subtração dos números será:", num1 - num2)
print("A multiplicação dos números será:", num1 * num2)
print("A divisão dos números será:", num1 / num2)
print()
print(nome+", hoje Aprendemos as operações básicas de matemática")

