# -*- coding: utf-8 -*-
"""exemplos_aula03_strings.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qwc3YQ0J9zjEamNiqK1LAxzDM0fjhduH

<a href="https://colab.research.google.com/github/gpereira-blueedtech/Blue_T3C5_mod1/blob/main/exemplos_aula03_strings.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>
"""

var1 = 250
var1a = 100
var2 = "250"
var2a = "100"
var3 = 'Batman "que ri" do quadrinho ' # Exemplo de uso de aspas dentro de umas string
var4 = "de um universo paralelo"
concatenacao = var3 + var4

print(type(var1))
print(type(var2))
print()
print(var2 + var2a)
print(concatenacao)

var0 = 250
var0a = 100
var1 = 'Batman "que ri" do quadrinho, ' # Exemplo de uso de aspas dentro de umas string
var2 = "de um universo paralelo"
frase = input("Digite qualquer coisa: ")

### len() -> retorna o tamanho da string (número de caracteres)
# print(len(var3))
# print(frase)


### string.capitalize() -> Transforma o primeiro CARACTERE de uma string em maiúscula, e o restante em minúscula.

# print(frase.capitalize())
# print("isso é uma string".capitalize())

# fraseCapitalize = input("digite algo minúsculo:").capitalize()
# print(fraseCapitalize)

### string.count("caracter") -> conta quantas vezes um caractere (ou sequência de caracteres) aparece em uma string
# print(var1.count("a"))
# contadorLetra = var1.count("a")
# print(contadorLetra)
# print(type(contadorLetra))

### string.startswith("teste") -> Verifica se a string começa com o que foi passado como argumento e retorna com True ou False
# print(var1.startswith("Bat"))

### string.isalnum() -> Verifica se a string possui apenas valor alfanumérico (letra ou número)
# print(var2.isalnum())
# print(frase)

### string.upper() e string.lower() -> Transforma todos os caracteres de uma string em maiúsculo ou minúsculo
# print(frase.upper())
# print(frase.lower())
# print()
# fraseUpper = frase.upper()
# print(fraseUpper)
# print()
# fraseInputUpper = input("Digite SIM ou NÃO: ").upper()
# print(fraseInputUpper)
# print()
# email = input("Digite seu email: ").lower()
# print(email)

### string.title() -> Retorna a string com todas os primeiros caracteres de cada palavra em maiúscula e o resto em minúscula: método preferido da T3C5
# print(var1.title())
# print(frase.title())
# print("isso é um exemplo".title())

### string.split() -> transforma cada elemento da string (tomando os espaços como referência) em um elemenmto de uma lista
# lista1 = var1.split()
# print(lista1)
# print(frase.split())

### string.replace("S1", "S2") -> substitui todos os caracteres passadops em S1 pelos passados em S2
# print(var1.replace("man","woman"))
# print("oi aluno".replace("oi","tchau").replace("aluno","aluna"))
print(var1.replace(" ",""))

# moeda = input("Digite o valor em Reais: ").replace(",",".") # Pegando valor entrado, substituindo , por . e já transformando em float para poder fazer cálculos
# # total = moeda + 10
# print(moeda)
# # print(total)

### string.strip() -> remove os espaços do começo e do final da string
# print(frase.strip())