# -*- coding: utf-8 -*-
"""PRIMEIROS_EXERCÍCIOS.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HcowpIYfWek-AT-ne7DbmTplh05Try24

<a href="https://colab.research.google.com/github/SteffanySympson/Blue-mod-1/blob/main/PRIMEIROS_EXERC%C3%8DCIOS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>
"""



"""01 - Elabore um programa que imprima na tela a seguinte frase Olá Mundo! Esse é o meu primeiro programa"""

print ('Olá Mundo!!!')
print ('Esse é o meu primeiro código! Eba!!!')
print ()
var1 = 'Blue'
var2 = 25
var3 = 18.1
var4 = True
print (var1)
print (var2)
print (var3)
print (var4)
print ()
print (type(var1))
print (type(var2))
print (type(var3))
print (type(var4))

"""02 - Elabore um programa que escreve seu nome completo na primeira linha, seu endereço na segunda e o CEP e telefone na terceira."""

print ("Nome: Steffany Sympson M. de Oliveira")
print () 
print ("Endereço: Est. do Encanamento nº 1826.")
print ()
print ("CEP: 23068-225")

"""03 - Elabore um programa que recebe o nome de uma pessoa do terminal e mostra a seguinte mensagem: Olá {nome}! Seja bem vindo ao fantástico mundo da programação"""

nome = input ("Qual o seu nome? ")
print ("Olá " + nome, "! Bem vindo (a) aos fantástico mundo da programação!" )