# -*- coding: utf-8 -*-
"""Aula01Blue Exercicios + Extras.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hfiqYL9elHGlIstgiCuRqTZsxCcyGVlb
"""

#
print ('Olá Mundo!!!')
print ('Esse é o meu primeiro código! Eba!!!')
print ()
var1 = 'Blue'
var2 = 25
var3 = 18.1
var4 = True
print (var1)
print (var2)
print (var3)
print (var4)
print ()
print (type(var1))
print (type(var2))
print (type(var3))
print (type(var4))

#EXERCÍCIO 1
#Dólar Americano = 5,04
# Euro = 6,13
# Libra Esterlina = 7,13
# Dólar Canadense = 4,16
# Peso Argentino = 0,053
# Peso Chileno = 0,0070

# Texto solicitando entrada de valor em reais
# Print dos valores multiplicados
# Print com o $
#converter valor para float

DolarAmericano = 5.04
Euro = 6.13
LibraEsterlina = 7.13
DolarCanadense = 4.16
PesoArgentino = 0.053
PesoChileno = 0.0070

nome = input ("Qual o seu nome? ")
print ("Olá!!! Bem vindo (a) " +nome, "ao conversor de moedas!")
print ()
ValorReal = float (input ("Informe o valor em Reais - R$ - para o resultado de conversão: "))
print ()
print (f"Dólar Americano: $ {(ValorReal / DolarAmericano):.2f}")
print ()
print (f"Euro: $ {(ValorReal / Euro):.2f}")
print ()
print (f"Libra Esterlina: $ {(ValorReal / LibraEsterlina):.2f}")
print ()
print (f"Dolar Canadense: $ {(ValorReal / DolarCanadense):.2f}")
print ()
print (f"Peso Argentino: $ {(ValorReal / PesoArgentino):.2f}")
print ()
print (f"Peso Chileno: $ {(ValorReal / PesoChileno):.2f}")
print ()

#Exercício Nº 2

#Imputar o valor do aluguel
#variável IGPM de 31% = 0.31

igpm = 0.31

nome = input ("Qual o seu nome? ")
print ("Olá!!! Bem vindo (a) " +nome, "a calculadora de aluguel!")
print ()
Aluguel = float (input ("Informe o valor em Reais - R$ - do seu aluguel: "))
Aumento = (Aluguel * igpm)
print ()
print (f"Total de Aumento: R$ {(Aumento):.2f}")
print (f"Valor Atualizado: R$ {(Aluguel + Aumento):.2f}")

#EXTRA 1
print ("Olá Mundo! Esse é o meu primeiro programa!")

#EXTRA 2

print ("Nome: Steffany Sympson M. de Oliveira")
print () 
print ("Endereço: Est. do Encanamento nº 1826.")
print ()
print ("CEP: 23068-225")

#EXTRA 3

nome = input ("Qual o seu nome? ")
print ("Olá " + nome, "! Bem vindo (a) aos fantástico mundo da programação!" )

#EXTRA 4
var_1 = int (input ("Olá! Informe a primeira variável: "))
var_2 = int (input ("Agora informe a segunda variável: "))
print ("Soma = ", var_1 + var_2)

#EXTRA 5

nota1 = float (input ("Olá! Informe a primeira nota: "))
nota2 = float (input ("Olá! Informe a segunda nota: "))
nota3 = float (input ("Olá! Informe a terceira nota: "))
nota4 = float (input ("Olá! Informe a quarta nota: "))
print ()
soma = nota1 + nota2 + nota3 + nota4
media = soma / 4
print ("A média é: ", media)

#EXTRA 6

valor1 = int(input ("Olá! Informe o primeiro valor: "))
valor2 = int(input ("Olá! Informe o segundo valor: "))
print (f'{valor1} é maior que {valor2}? {valor1 > valor2}')
print (f'{valor1} é igual a {valor2}? {valor1 == valor2}')