# -*- coding: utf-8 -*-
"""Exercícios_Fatiamento_e_Manipulação_de_String.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1x8K4pogaY_FsrLI2ckVW7SoTP8Z3CLbn

<a href="https://colab.research.google.com/github/SteffanySympson/Blue-mod-1/blob/main/Exerc%C3%ADcios_Fatiamento_e_Manipula%C3%A7%C3%A3o_de_String.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Considere a string A = "Os limites só existem se você os deixar existir.(goku)".

Que fatia corresponde a (goku)?
"""

A = "Os limites só existem se você os deixar existir.(goku)"
len(A)
print (A[48:])

""" Escreva um programa que solicite uma frase ao usuário e escreva a frase toda em maiúscula e sem espaços em branco."""

Frase = input ("Escreva uma frase para teste: \n" )
print (Frase.upper().replace(" ",""))

"""Elabore um programa que recebe o seu nome, endereço e hobby e mostra cada uma das informações da seguinte forma:

Nome -> Letra maiúscula
Endereço -> Letra minúscula
Hobby -> Primeira letra maiúscula
"""

nome = input ("Digite seu nome completo: ")
print (nome.upper())
print()
endereço = input ("Digite seu endereo: ")
print (endereço.lower())
print ()
hobby = input ("Qual seu hobby: ")
print (hobby.capitalize())

"""Escreva um programa que deve receber o nome completo do usuário e retornar uma saudação com o nome no formato adequado (todas as primeiras letras em maiúsculas)."""

nome = input ("Informe seu nome completo: ").title ()
print ("Olá ", nome, " Seja bem vindo!")

"""Faça um programa que solicite a altura e o peso do usuário, e calcule o seu IMC. Os dados entrados precisam ser corrigidos pelo programa (trocando “,” por “.” e eliminando espaços e letras extras)."""

print ("Calculadora de IMC")
print ()
peso = float (input("Informe seu peso:\nKG: ").lower().replace(',','.').replace('k','').replace('g','').replace(' ',''))
altura = float (input("Informe sua altura:\nM: ").lower().replace(',','.').replace('m','').replace(' ', ''))
print()
imc = peso / (altura**2)
print (f"O seu IMC é: {imc:.1f}")